Finoa-Consensus-Services gentx
celestiaorg/networks pull request #415
Opened 2023-10-23 13:38 UTC by puneetfinoa

## Overview

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

2023-10-23 19:42 UTC, YazzyYaz approved these changes

2023-10-24 15:13 UTC, liamsi requested changes
Thanks for updating but can you instead follow the follwing:

---

Please make the peers and gentx separate files, so that your PR looks like this:

celestia/gentx/validatorname.json // 
celestia/validatorname.txt //

Afterwards we will consolidate all the peers from your txt files to peers.txt. Reason we ask is because merging PRs the way they are now is slow and problematic. Thank you for your understanding!

2023-10-24 15:16 UTC, puneetfinoa commented
> Thanks for updating but can you instead follow the follwing:
> 
> Please make the peers and gentx separate files, so that your PR looks like this:
> 
> celestia/gentx/validatorname.json // celestia/validatorname.txt //
> 
> Afterwards we will consolidate all the peers from your txt files to peers.txt. Reason we ask is because merging PRs the way they are now is slow and problematic. Thank you for your understanding!

I have made the changes

2023-10-24 18:51 UTC, liamsi requested changes

2023-10-24 18:51 UTC, liamsi commented on celestia/peers.txt
> -
Can you simply not change this file at all, please? Otherwise there are merge conflicts etc.

2023-10-24 19:46 UTC, closed without merging