Added 4sv peer and gentx
celestiaorg/networks pull request #424
Opened 2023-10-23 15:41 UTC by shivlim

## Overview

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

2023-10-23 20:37 UTC, YazzyYaz submitted a review, later dismissed

2023-10-24 13:44 UTC, liamsi approved these changes

2023-10-24 13:53 UTC, adlerjohn approved these changes

2023-10-24 14:05 UTC, liamsi requested changes
can you merge in the latest master from here?

2023-10-24 14:11 UTC, liamsi approved these changes
nvm

2023-10-24 14:11 UTC, merged