Create seeds.txt
celestiaorg/networks pull request #445
Opened 2023-10-24 09:36 UTC by easy2stake

Created at the suggestion of 'mindstyle | pops.one' on the Discord channel.

## Overview

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

2023-10-25 00:09 UTC, adlerjohn commented on celestia/seeds.txt
> +3d5661f41dbc64156fc0ba17b0def4106a887823@celestia-seed.easy2stake.com:26756
```suggestion
3d5661f41dbc64156fc0ba17b0def4106a887823@celestia-seed.easy2stake.com:26756
```

2023-10-25 13:02 UTC, YazzyYaz requested changes
make a file called easy2stake.txt with just your peer in it: 3d5661f41dbc64156fc0ba17b0def4106a887823@celestia-seed.easy2stake.com:26756

2023-10-25 13:38 UTC, mindstyle85 commented
justa fyi this is a seed peer, so should be separate in seeds.txt not peers.txt @YazzyYaz @adlerjohn

2023-10-27 15:12 UTC, easy2stake reviewed
I've updated the file, and removed the comments. 
The node is up, P2P port updated, and seed mode enabled !

2026-05-21 08:36 UTC, closed without merging