Update README.md with public dashboards
celestiaorg/networks pull request #530
Opened 2023-12-12 13:57 UTC by Bidon15

## Overview

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

2023-12-12 16:17 UTC, jcstein commented on README.md
> +DA Full and Light nodes might have troubles connecting to the networks, so you can checkout this [Grafana dashboard](https://celestia.grafana.net/public-dashboards/a10eff0043bb4bf0839004e2746e2bc6) t
```suggestion
DA Full and Light nodes might have troubles connecting to the networks, so you can checkout this [Grafana dashboard](https://celestia.grafana.net/public-dashboards/a10eff0043bb4bf0839004e2746e2bc6) to see health/uptime status of DA Bootstrappers (now `celestia` network only).
```

2023-12-12 16:20 UTC, jcstein requested changes
small nit

2023-12-13 14:22 UTC, jcstein approved these changes
:shipit:

2023-12-14 10:59 UTC, smuu approved these changes

2023-12-14 11:07 UTC, liamsi approved these changes

2023-12-14 11:07 UTC, merged